---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
  - name: check if user exists
    shell: id -u "{{item}}"
    register: user_exists
    ignore_errors: true
    with_items:
     - elevated1
     - elevated2
     - elevated3 

  - name: set 30d expire
    when: user_exists.rc == 0 
    command: passwd -x 30 "{{item}}"
