---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
  - name: check if user exists
    shell: id -u elevated2 
    register: user_exists
    ignore_errors: true

  - name: set 30d expire
    when: user_exists.rc == 0 
    command: passwd -x 30 elevated2
