---
- hosts: all
  gather_facts: no
  become: no

  vars_prompt:
  - name: "root_password"
    prompt: "Enter root password"
    private: yes

  tasks:
  - name: verify password by su
    expect:
     command: /bin/bash -c "su -"
     responses:
      Password for root: "{{root_password}}"
