---
- hosts: all
  gather_facts: no
  become: yes
  
  vars_prompt:
   - name: "username"
     prompt: "Please enter the username"
     private: no
     default: getronics
   - name: "password"
     prompt: "Please enter the password"
     private: yes
     encrypt: "sha512_crypt"
     confirm: yes
     salt_size: 7
     salt: "ifis_salt"

  tasks:
   - name: Update root Password
     user:
      name: "{{username}}"
      update_password: always
      password: "{{password}}"
