---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
   - name: Update root Password
     user:
      name: root
      update_password: always
      password: "{{lookup ('file', 'files/dev_password_file.txt') | password_hash('sha512', 'ifis_salt')}}"
